import Header from '@/layouts/header'
import type { Metadata } from 'next'
import { figtree } from '@/lib/fonts'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${figtree.className} antialiased w-full min-h-dvh bg-[#FAFAF9] text-base grid grid-rows-[auto_1fr]`}
      >
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
